--Weather Observation 1
SELECT CITY,STATE FROM STATION

--Weather Observation 2
SELECT CAST(ROUND(SUM(LAT_N),2) as numeric(36,2)),
CAST(ROUND(SUM(LONG_W),2) as numeric(36,2)) FROM STATION

--Weather Observation 3
SELECT DISTINCT CITY FROM STATION
WHERE ID%2=0

--Weather Observation 4
SELECT ((SELECT COUNT(CITY) FROM STATION) - 
(SELECT COUNT(DISTINCT CITY) FROM STATION)) 

--Weather Observation 5
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY),CITY;
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) DESC,CITY;

--Weather Observation 6
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE "a%" OR 
CITY LIKE "e%" OR
CITY LIKE "i%" OR
CITY LIKE "o%" OR
CITY LIKE "u%"

--Weather Observation 7
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE "%a" OR 
CITY LIKE "%e" OR
CITY LIKE "%i" OR
CITY LIKE "%o" OR
CITY LIKE "%u"

--Weather Observation 8
SELECT DISTINCT CITY FROM STATION
WHERE (CITY LIKE "a%" OR 
CITY LIKE "e%" OR
CITY LIKE "i%" OR
CITY LIKE "o%" OR
CITY LIKE "u%") 
AND 
(CITY LIKE "%a" OR 
CITY LIKE "%e" OR
CITY LIKE "%i" OR
CITY LIKE "%o" OR
CITY LIKE "%u")

--Weather Observation 9
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE "a%" AND
CITY NOT LIKE "e%" AND
CITY NOT LIKE "i%" AND
CITY NOT LIKE "o%" AND
CITY NOT LIKE "u%" 

--Weather Observation 10
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE "%a" AND
CITY NOT LIKE "%e" AND
CITY NOT LIKE "%i" AND
CITY NOT LIKE "%o" AND
CITY NOT LIKE "%u" 

--Weather Observation 11
SELECT DISTINCT CITY FROM STATION
WHERE (CITY NOT LIKE "a%" AND
CITY NOT LIKE "e%" AND
CITY NOT LIKE "i%" AND
CITY NOT LIKE "o%" AND
CITY NOT LIKE "u%") 
OR
(CITY NOT LIKE "%a" AND 
CITY NOT LIKE "%e" AND
CITY NOT LIKE "%i" AND
CITY NOT LIKE "%o" AND
CITY NOT LIKE "%u")

--Weather Observation 12
SELECT DISTINCT CITY FROM STATION
WHERE (CITY NOT LIKE "a%" AND
CITY NOT LIKE "e%" AND
CITY NOT LIKE "i%" AND
CITY NOT LIKE "o%" AND
CITY NOT LIKE "u%") 
AND
(CITY NOT LIKE "%a" AND 
CITY NOT LIKE "%e" AND
CITY NOT LIKE "%i" AND
CITY NOT LIKE "%o" AND
CITY NOT LIKE "%u")

--Weather Observation 13
SELECT CAST(ROUND(SUM(LAT_N),4) as numeric(10,4)) FROM STATION
WHERE LAT_N>38.7880 AND LAT_N<137.2345

--Weather Observation 14
SELECT MAX(CAST(ROUND((LAT_N),4) as numeric(10,4))) FROM STATION
WHERE LAT_N<137.2345

--Weather Observation 15
SELECT TOP 1 CAST(ROUND((LONG_W),4) as numeric(10,4))
FROM STATION WHERE (LAT_N<137.2345)
ORDER BY (LAT_N) DESC

--Weather Observation 16
SELECT TOP 1 CAST(ROUND((LAT_N),4) as numeric(10,4))
FROM STATION WHERE (LAT_N>38.7780)
ORDER BY (LAT_N) ASC

--Weather Observation 17
SELECT TOP 1 CAST(ROUND((LONG_W),4) as numeric(10,4))
FROM STATION WHERE (LAT_N>38.7780)
ORDER BY (LAT_N) ASC